import fs from 'fs';
import path from 'path';

// Let's create the master data file directly
const facultyCSVLines = [
  [1, "Dr. S. Venkateswarlu", "Principal", "ECE", "M.Tech., Ph.D", "Dr. S. Venkateswarlu is the Principal of NEC with 38+ years of academic and administrative experience. Specializes in Wireless Channel Simulation, Mobile Communications, and Network Architectures. Authored 125+ research papers."],
  [2, "Dr. P. Naga Sowjanya", "Assoc. Professor & HOD", "CE", "M.Tech, Ph.D", "Dr. P. Naga Sowjanya has 13+ years experience with Ph.D from NIT Warangal. Research focus on Climate Change, Water Resources, GIS & Hydrological Modelling."],
  [3, "Dr. A. Ranganathan", "Professor", "CE", "M.E., Ph.D.", "Expertise in Structural Engineering, Concrete Technology, and Earthquake Resistant Design."],
  [4, "Dr. G. Venkateswarlu", "Professor", "CE", "M.Tech, Ph.D", "Specializes in Geotechnical Engineering, Foundation Engineering, and Soil Dynamics."],
  [5, "Dr. K. Hari krishna", "Professor", "CE", "M.Tech, Ph.D", "Expertise in Transportation Engineering, Highway Materials, and Traffic Management."],
  [6, "K. Anil Kumar", "Asst. Prof.", "CE", "M.Tech", "Research focus on Environmental Engineering and Sustainable Construction."],
  [7, "N. Mb. Subhani", "Asst. Prof.", "CE", "M.Tech", "Specializes in Seismic Evaluation of RC Framed Buildings and Structural Health."],
  [8, "K. Meghanadh", "Asst. Prof.", "CE", "M.Tech", "Research on Strength Properties of Concrete with industrial byproducts."],
  [9, "M. Vasavi", "Asst. Prof.", "CE", "M.Tech", "Structural Engineering and Material testing specialist."],
  [10, "M. N. S. Samba Siva Rao", "Asst. Prof.", "CE", "M.Tech", "Smart Pavement and Highway Structural systems."],
  [11, "A. Lakshmi Prasanna", "Asst. Prof.", "CE", "M.Tech", "Concrete technology with partial replacement using industrial minerals."],
  [12, "S. Maheswari", "Asst. Prof.", "CE", "M.Tech", "Hydraulics and Water Resource Management."],
  [13, "Sk. Sydha", "Asst. Prof.", "CE", "M.Tech", "Fiber Self-Compacting Concrete research and development."],
  [14, "M. Venkatesh", "Asst. Prof.", "CE", "M.Tech", "Surveying, Remote Sensing, and GIS."],
  [15, "B.V.Srinivasa Rao", "Asst. Prof.", "CE", "M.Tech", "Structural Dynamics and Finite Element Analysis."],
  [16, "G. Ezri Babu", "Asst. Prof.", "CE", "M.Tech", "Construction Technology and Project Management."],
  [17, "Pathan sardar khan", "Asst. Prof.", "CE", "M.Tech", "Geotechnical investigations and Foundation analysis."],
  [18, "Dr. P. Hari krishna Prasad", "Professor", "EEE", "M.Tech., Ph.D", "Power Systems, Renewable Energy Integration, and Smart Grids."],
  [19, "Dr. Y. Srinivasa Rao", "Professor", "EEE", "M.Tech., Ph.D", "High Voltage Engineering and Electrical Insulation."],
  [20, "Dr. P. Sarath Kumar", "Professor", "EEE", "M.Tech, Ph.D", "Power Electronics and Motor Drives."],
  [21, "Dr. R. Shankar", "Assoc. Professor", "EEE", "M.Tech, Ph.D", "Control Systems and Industrial Automation."],
  [22, "Dr. K. Raghavendra Reddy", "Assoc. Professor", "EEE", "M.Tech, Ph.D", "Smart Grid Technologies and Energy Storage."],
  [23, "Dr. SK. Md. Shareef", "Assoc. Professor & HOD", "EEE", "M.Tech., Ph.D", "HOD of EEE. Authored books on Network Analysis & Electrical Circuit Analysis; holder of 5+ patents in Smart Grid and EV converters."],
  [24, "P.D.V.S.K.Kishore", "Asst. Prof.", "EEE", "M.Tech", "Sustainable EV Charging Stations and Smart Metering."],
  [25, "G.Naga Raju", "Asst. Prof.", "EEE", "M.Tech.", "Power Systems Operation and Planning."],
  [26, "M.Chandra Sekhar", "Asst. Prof.", "EEE", "M.Tech.", "AI-Powered Smart Metering and Load Forecasting."],
  [27, "SK.Karimulla", "Asst. Prof.", "EEE", "M.Tech", "Renewable Energy Systems and Battery Management."],
  [28, "B.Praveen Kumar", "Asst. Prof.", "EEE", "M.Tech", "Power Quality Improvement and Active Filters."],
  [29, "G.Naveen", "Asst. Prof.", "EEE", "M.Tech.", "Dual Power Source EV Energy Management Systems."],
  [30, "A.Jyostana Bhavani", "Asst. Prof.", "EEE", "M.Tech", "Electric Drives and Embedded Controllers."],
  [31, "B.V.Pavan Sunil Kumar", "Asst. Prof.", "EEE", "M.Tech", "Power System Protection and Switchgear."],
  [32, "N.Teji Lal", "Asst. Prof.", "EEE", "M.Tech", "Microgrids and Distributed Generation."],
  [33, "J.Siva Prakash", "Asst. Prof.", "EEE", "M.Tech", "High Power Converters and FACTS Devices."],
  [34, "M. Subramanyam", "Asst. Prof.", "EEE", "M.Tech", "Industrial Electrical Systems and PLC SCADA."],
  [35, "M.Syam Kumar", "Asst. Prof.", "EEE", "M.Tech", "Solar Photovoltaic System Design."],
  [36, "Sk. Abdul Kalam", "Asst. Prof.", "EEE", "M.Tech", "AI-Enabled Battery Management Systems."],
  [37, "G. Naga Vardhani", "Asst. Prof.", "EEE", "M.Tech", "Control Systems and Signal Conditioning."],
  [38, "P. Bramaramba Vathi", "Asst. Prof.", "EEE", "M.Tech", "Adaptive Energy Management Systems."],
  [39, "P. Raghava Rani", "Asst. Prof.", "EEE", "M.Tech", "Smart Grid Automation and Metering."],
  [40, "D.V. Srinivasa Rao", "Asst. Prof.", "EEE", "M.Tech", "Electrical Machine Design and Testing."],
  [41, "G. Kranthi Kumari", "Asst. Prof.", "EEE", "M.Tech", "Power Electronics Applications in Power Systems."],
  [42, "B. Nagaiah", "Asst. Prof.", "EEE", "M.Tech", "Transmission Line Optimization."],
  [43, "J. Indira Priyadarsini", "Asst. Prof.", "EEE", "M.Tech", "Renewable Energy Economics and Grid Compliance."],
  [44, "M. Gowthami", "Asst. Prof.", "EEE", "M.Tech", "Smart Electric Vehicle Charging Infrastructure."],
  [45, "K. Silpa", "Asst. Prof.", "EEE", "M.Tech", "Hybrid Solar-Wind Converter Design."],
  [46, "T.Sudhakar", "Asst. Prof.", "EEE", "M.Tech", "Digital Signal Processing in Power Applications."],
  [47, "M. Ratna Kishore", "Asst. Prof.", "EEE", "M.Tech", "Power Distribution Reliability Analysis."],
  [48, "Dr. D. Suneel", "Professor & Dean (First Year) / Vice Principal", "MEC", "M.Tech, Ph.D", "Mechanical academic leader, 23 yrs exp, 30+ papers, 20 design patents, 2 innovation patents, 50 Coursera/NPTEL certs."],
  [49, "Dr. B. Venkata Siva", "Professor & HOD", "MEC", "M.Tech, Ph.D", "HOD of Mechanical Engineering; FIE(I), ASME member; 20+ research articles (7 SCI, 8 Scopus), 20 design patents, 2 utility patents."],
  [50, "Dr. M . Ramakotaiah", "Professor", "MEC", "M.Tech., Ph.D", "Thermal Engineering, CFD, and Heat Transfer."],
  [51, "Dr. P.Suresh Babu", "Assoc. Professor", "MEC", "M.E., Ph.D", "Manufacturing Engineering and Robotics."],
  [52, "M. Venkaiah", "Assoc. Professor", "MEC", "M.Tech.", "AICTE IDEA Lab Tech Guru; CAD/CAM and Additive Manufacturing."],
  [53, "P.Srinivasa Rao", "Assoc. Professor", "MEC", "M.Tech.", "Design Engineering and Finite Element Analysis."],
  [54, "Ch. Sekhar", "Assoc. Professor", "MEC", "M.Tech", "Production Engineering and Metal Forming."],
  [55, "K.Kiran Chand", "Assoc. Professor", "MEC", "M.Tech", "Mechatronics and Automation."],
  [56, "Dr. M. Venkanna Babu", "Asst. Prof.", "MEC", "M.Tech, Ph.D", "Composite Materials and Nanotechnology."],
  [57, "P. Sravani", "Asst. Prof.", "MEC", "M.Tech", "Thermal and Stress Analysis using Functional Graded Materials."],
  [58, "T.Ashok Kumar", "Asst. Prof.", "MEC", "M.Tech", "Refrigeration and Air Conditioning."],
  [59, "G.Bhargav", "Asst. Prof.", "MEC", "M.Tech.", "Fluid Mechanics and Turbomachinery."],
  [60, "K. John Babu", "Asst. Prof.", "MEC", "M.Tech", "AICTE IDEA Lab Tech Guru; Rapid Prototyping and 3D Printing."],
  [61, "A. Pavan Kumar", "Asst. Prof.", "MEC", "M.Tech", "IC Engines and Alternate Fuels."],
  [62, "D. Raghavendra", "Asst. Prof.", "MEC", "M.Tech", "Industrial Engineering and Ergonomics."],
  [63, "Y. Suvarna Kumar", "Asst. Prof.", "MEC", "M.Tech", "Machining Science and Tool Design."],
  [64, "M. Mothilal Naik", "Asst. Prof.", "MEC", "M.Tech", "Welding Technology and Metallurgy."],
  [65, "D. Gopi", "Asst. Prof.", "MEC", "M.Tech", "Robotics and Collaborative Automation."],
  [66, "U. Naga Raju", "Asst. Prof.", "MEC", "M.Tech", "Vibration Analysis and Condition Monitoring."],
  [67, "D. Ratna Babu", "Asst. Prof.", "MEC", "M.Tech", "Hydraulics and Pneumatics."],
  [68, "P. Kiran Kumar", "Asst. Prof.", "MEC", "M.Tech", "Mechanics of Solids and Fracture Mechanics."],
  [69, "Dr. V. Venkata Rao", "Professor & HOD", "ECE", "M.E., Ph.D", "HOD of ECE; IEEE Senior Member (94721103), ISTE LM 60635; ORCID: 0001-9251-2406; Scopus: 57215069303; 3 patents."],
  [70, "Dr. R. Siva Kumar", "Professor", "ECE", "M.Tech., Ph.D", "Signal Processing, VLSI Design, and FPGA Implementation."],
  [71, "Dr. N. Veda Kumar", "Professor", "ECE", "M.Tech., Ph.D", "Wireless Sensor Networks and IoT Architectures."],
  [72, "Dr. K. Raju", "Professor", "ECE", "M.Tech., Ph.D", "AICTE IDEA Lab Tech Guru; Biomedical Signal Processing and Bioimpedance Artifact Canceller patent holder."],
  [73, "Dr. J. Brahamaih Naik", "Professor", "ECE", "M.Tech, Ph.D", "Antenna Design, Microwave Engineering, and Electromagnetics."],
  [74, "P.S.S. Chakravarthi", "Assoc. Professor", "ECE", "M.Tech.", "Embedded Systems and Microcontrollers."],
  [75, "J. Narasimha Rao", "Assoc. Professor", "ECE", "M.Tech.", "Digital Communications and Information Theory."],
  [76, "N. Srinivasa Rao", "Assoc. Professor", "ECE", "M.Tech.", "Radar Systems and Navigation Aids."],
  [77, "P. Bhagya Raju", "Assoc. Professor", "ECE", "M.Tech.", "Low Power CMOS VLSI Design."],
  [78, "Dr. R. Dinesh Kumar", "Assoc. Professor", "ECE", "M.E., Ph.D.", "Image Processing and Pattern Recognition."],
  [79, "Dr. G. Ram Prabhu", "Assoc. Professor", "ECE", "M.E., Ph.D.", "Wireless Communications and Channel Modeling."],
  [80, "Dr. S. Sivalingam", "Assoc. Professor", "ECE", "M.E., Ph.D.", "Optoelectronics and Optical Fiber Communications."],
  [81, "Dr. Y. Jaipal Reddy", "Assoc. Professor", "ECE", "M.Tech., Ph.D", "Computer Vision and Edge AI."],
  [82, "Dr. Ebraheem Kaleelulla", "Assoc. Professor", "ECE", "M.Tech., Ph.D", "DSP Architecture and SoC Design."],
  [83, "Dr. Md. Javeed Ahamed", "Assoc. Professor", "ECE", "M.Tech, Ph.D", "AICTE IDEA Lab Tech Guru; Sensor Interfacing and Microcontroller Applications."],
  [84, "Dr. P. Srikanth", "Assoc. Professor", "ECE", "M.Tech, Ph.D", "MEMS and Microelectronics."],
  [85, "Dr. M. Srinivasulu", "Assoc. Professor", "ECE", "M.Tech, Ph.D", "Telecommunication Switching Systems and Networks."],
  [86, "Dr. B. Suneetha", "Assoc. Professor", "ECE", "M.Tech., Ph.D", "3 Published Patents in Hand Sanitizer Automation, Retinal Disease ML, and Public Disinfection Systems."],
  [87, "Dr. K. Srinivasarao", "Assoc. Professor", "ECE", "M.Tech, Ph.D", "Nanoelectronics and Semiconductor Devices."],
  [88, "Dr. Y.V. Lakshmaiah", "Assoc. Professor", "ECE", "M.Tech, Ph.D", "Wireless Ad-hoc Networks."],
  [89, "Dr. B. Siva Nageswararao", "Assoc. Professor", "ECE", "M.Tech, Ph.D", "Array Signal Processing and MIMO."],
  [90, "Dr. K.Sheela", "Assoc. Professor", "ECE", "M.Tech, Ph.D", "Biomedical Instrumentation."],
  [91, "Dr. Sk. Nannu Saheb", "Assoc. Professor", "ECE", "M.Tech., Ph.D", "RF and Microwave Circuit Design."],
  [92, "Dr. T. Naga Swathi", "Asst. Prof.", "ECE", "M.Tech., Ph.D", "Digital VLSI and Verification."],
  [93, "V.Naveen Raja", "Asst. Prof.", "ECE", "M.Tech", "Speech Processing and Audio AI."],
  [94, "A.Raveendra Babu", "Asst. Prof.", "ECE", "M.Tech", "Satellite Communication."],
  [95, "T.Indira", "Asst. Prof.", "ECE", "M.Tech", "Analog Circuits and IC Design."],
  [96, "N.Narayana", "Asst. Prof.", "ECE", "M.Tech", "Cellular and Mobile Communications."],
  [97, "Shaik Mohammed Umar", "Asst. Prof.", "ECE", "M.Tech", "Robotics and IoT Sensors."],
  [98, "A. Venkata Siva", "Asst. Prof.", "ECE", "M.Tech.", "Signals and Systems."],
  [99, "N. Dasaradh", "Asst. Prof.", "ECE", "M.Tech.", "Electromagnetic Wave Propagation."],
  [100, "J. Pallavi", "Asst. Prof.", "ECE", "M.Tech", "VLSI Physical Design."],
  [101, "G. S. Joe victor", "Asst. Prof.", "ECE", "M.Tech", "Digital System Design."],
  [102, "Ch. Adi Babu", "Asst. Prof.", "ECE", "M.Tech", "Wireless Networks."],
  [103, "B. Srinivasarao", "Asst. Prof.", "ECE", "M.Tech", "Embedded C and ARM Programming."],
  [104, "Sk. Asifa", "Asst. Prof.", "ECE", "M.Tech", "Digital Image Processing."],
  [105, "M. Hari Haranadha Sastry", "Asst. Prof.", "ECE", "M.Tech", "Microprocessors and Interfacing."],
  [106, "G. Rajavali", "Asst. Prof.", "ECE", "M.Tech", "Broadband Communications."],
  [107, "Sk. Md. Shareef", "Asst. Prof.", "ECE", "M.Tech", "Electronic Devices and Circuits."],
  [108, "P. Jayababu", "Asst. Prof.", "ECE", "M.Tech", "Computer Communication Networks."],
  [109, "P. Vinuthna", "Asst. Prof.", "ECE", "M.Tech", "FPGA Architecture."],
  [110, "D. Suneel", "Asst. Prof.", "ECE", "M.Tech", "Smart Sensor Technologies."],
  [111, "CH. Seshu kumar", "Asst. Prof.", "ECE", "M.Tech", "Radar and Optical Communications."],
  [112, "G. Ramana Reddy", "Asst. Prof.", "ECE", "M.Tech", "Antennas and Propagation."],
  [113, "M. B. Narendra", "Asst. Prof.", "ECE", "M.Tech", "Linear Integrated Circuits."],
  [114, "A. Ramesh", "Asst. Prof.", "ECE", "M.Tech", "Digital Signal Processors."],
  [115, "B. Baburao", "Asst. Prof.", "ECE", "M.Tech", "Microwave Tubes and Solid State Devices."],
  [116, "P.V. Narendra", "Asst. Prof.", "ECE", "M.Tech", "VLSI Testing and Testability."],
  [117, "Sk. Ahammad", "Asst. Prof.", "ECE", "M.Tech", "Telecommunication Networks."],
  [118, "M.V. Suneetha", "Asst. Prof.", "ECE", "M.Tech", "Electronic Instrumentation."],
  [119, "N. Naga Lakshmi", "Asst. Prof.", "ECE", "M.Tech", "Wireless Sensor Networks."],
  [120, "K. Narasimha Rao", "Asst. Prof.", "ECE", "M.Tech", "Digital Electronics."],
  [121, "P. V. Satish Kumar", "Asst. Prof.", "ECE", "M.Tech", "Control Systems Engineering."],
  [122, "K. Bhulakshmi", "Asst. Prof.", "ECE", "M.Tech", "Biomedical Engineering."],
  [123, "M. Sri Lakshmi", "Asst. Prof.", "ECE", "M.Tech", "CMOS Analog Design."],
  [124, "N. Satyanarayana", "Asst. Prof.", "ECE", "M.Tech", "High Speed Networking."],
  [125, "Purne Srinivasa Rao", "Asst. Prof.", "ECE", "M.Tech", "Digital Signal Processing."],
  [126, "P.Shajahan", "Asst. Prof.", "ECE", "M.Tech", "Optical Networks."],
  [127, "R.Sama Naik", "Asst. Prof.", "ECE", "M.Tech", "Network Security Protocols."],
  [128, "Sk.Lal john Basha", "Asst. Prof.", "ECE", "M.Tech", "VLSI Design."],
  [129, "K.Peda raju", "Asst. Prof.", "ECE", "M.Tech", "Electronics & Instrumentation."],
  [130, "G.Deena sundararao", "Asst. Prof.", "ECE", "M.Tech", "Embedded Architectures."],
  [131, "Sk.Shakeera", "Asst. Prof.", "ECE", "M.Tech", "Signals and Systems."],
  [132, "K.Chaitanya", "Asst. Prof.", "ECE", "M.Tech", "Microcontrollers."],
  [133, "T.Suresh", "Asst. Prof.", "ECE", "M.Tech", "Wireless Networks."],
  [134, "R.Anji Naik", "Asst. Prof.", "ECE", "M.Tech", "Digital Communications."],
  [135, "P.Ravi kumar", "Asst. Prof.", "ECE", "M.Tech", "Microwave Engineering."],
  [136, "Dr. S. N. Tirumala Rao", "Professor & HOD", "CSE", "M.Tech., Ph.D.", "HOD of Computer Science & Engineering; 26+ research papers, citation count 75, h-index 5; specialist in Alzheimer's diagnosis using deep learning & metaheuristic optimization."],
  [137, "Dr. S. V. N. Srinivasu", "Professor & Dean R&D", "CSE", "M.Tech., Ph.D.", "Dean R&D; 60+ publications, 6 patents, citation count 57, h-index 5; AICTE IDEA Lab Coordinator; Specialist in IoT and Fast Recurrent Neural Networks."],
  [138, "Dr. K. Lakshminadh", "Professor", "CSE", "M.Tech., Ph.D.", "13+ publications; Distributed Computing, Cloud Architectures and Big Data Systems."],
  [139, "Dr. S. Siva Nageswara Rao", "Professor", "CSE", "M.Tech., Ph.D.", "16+ publications; Natural Language Processing, Machine Learning, and Information Retrieval."],
  [140, "Dr. V. V. A. S. Lakshmi", "Professor & HOD (AI&ML/CS/DS)", "CSE", "M.Tech., Ph.D.", "HOD of CSE AI&ML, Cyber Security and Data Science; 21 years teaching experience, 40+ research papers, patent on ML defect detection."],
  [141, "Dr. Sk. Chand Badsha", "Professor", "CSE", "M.Tech., Ph.D.", "Cyber Security, Cryptography, and Blockchain Technologies."],
  [142, "Dr. S. Ganesh Babu", "Professor", "CSE", "M.Tech., Ph.D.", "Data Mining, Data Warehousing, and Predictive Analytics."],
  [143, "Dr. G. Dileep Kumar", "Professor", "CSE", "M.Tech., Ph.D.", "Computer Networks, Network Security, and Protocol Engineering."],
  [144, "Dr. B. Jayachandran", "Professor", "CSE", "M.E., Ph.D", "Software Engineering, Agile Methodologies, and Software Quality Assurance."],
  [145, "Dr. G. Vijaya Kumar", "Professor", "CSE", "M.Tech, Ph.D", "Artificial Intelligence, Knowledge Representation, and Neural Networks."],
  [146, "Dr. O. Samba Siva Rao", "Professor", "CSE", "M.Tech., Ph.D.", "Database Management Systems and Advanced Database Architectures."],
  [147, "Dr. B. Sreedhar", "Professor", "CSE", "M.Tech., Ph.D.", "Operating Systems, Distributed Systems, and High Performance Computing."],
  [148, "Dr. V. Venu gopal", "Professor", "CSE", "M.Tech., Ph.D.", "Web Technologies, Full Stack Development, and Cloud Native Architectures."],
  [149, "Dr. M. Manoj Kumar", "Professor", "CSE", "M.E., Ph.D", "Deep Learning, Image Processing, and Computer Vision."],
  [150, "V. Mahesh Babu", "Professor & Controller of Examinations", "CSE", "M.Tech.", "Controller of Examinations; Nominee of Principal on Academic Council; Computer Networks and Cloud Computing."],
  [151, "Dr. M. Sireesha", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "17+ publications, citation count 18; Data Science and Bio-informatics."],
  [152, "Dr. A. Mahendar", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "Mobile Ad-hoc Networks and Sensor Networks."],
  [153, "Dr. K. Ashok", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "Information Security and Secure Software Development."],
  [154, "Dr. M. Malyadri", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "Machine Learning and Pattern Recognition."],
  [155, "Dr. T. Nedhunchezhian", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "Natural Language Processing and Sentiment Analysis."],
  [156, "Dr. E. Rama Krishna", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "Cloud Computing and Virtualization Technologies."],
  [157, "Dr. S. Venkatesan", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "Big Data Analytics and Stream Processing."],
  [158, "Dr. S. Vasantha Swaminathan", "Assoc. Professor", "CSE", "M.E., Ph.D.", "Software Testing and Automated Quality Control."],
  [159, "Dr. G. Siva Raman", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "Internet of Things and Smart Applications."],
  [160, "Dr. T. Muni Sankar", "Assoc. Professor", "CSE", "M.Tech, Ph.D", "Cyber Security and Digital Forensics."],
  [161, "Dr. R. Ramnath", "Assoc. Professor", "CSE", "M.Tech, Ph.D", "Computer Architecture and Embedded Systems."],
  [162, "Dr. Y. Leelakrishna", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "Theory of Computation and Compiler Design."],
  [163, "Dr. G. Prasanth", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "Data Science and Statistical Modeling."],
  [164, "Dr. S. Janakiramudu", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "Computer Vision and Medical Image Analysis."],
  [165, "Dr. B. Srikanth", "Assoc. Professor", "CSE", "M.Tech., Ph.D.", "Algorithms and Complexity Theory."],
  [166, "Dr. CH. Venkata Ratnam", "Assoc. Professor", "CSE", "M.Tech, Ph.D.", "Artificial Neural Networks and Deep Learning."],
  [167, "Dr. P. Marimuthu", "Assoc. Professor", "CSE", "M.E., Ph.D", "Distributed Databases and Consensus Protocols."],
  [168, "Dr. S. Jeyam", "Assoc. Professor", "CSE", "M.E., Ph.D", "Edge Computing and Wireless Sensor Systems."],
  [169, "N. Vijaya Kumar", "Assoc. Professor", "CSE", "M.Sc., M.E..", "Object Oriented Analysis and Java Technologies."],
  [170, "Sd. Rizwana", "Asst. Prof.", "CSE", "M.Tech.", "Data Structures and Python Programming."],
  [171, "P. Swathi", "Asst. Prof.", "CSE", "M.Tech.", "Database Management Systems and SQL."],
  [172, "Sk. Subhani", "Asst. Prof.", "CSE", "M.Tech.", "Web Development and JavaScript Frameworks."],
  [173, "SK. Gousya Pyari", "Asst. Prof.", "CSE", "M.Tech.", "Operating Systems and Shell Programming."],
  [174, "Sk. Khaja Mohiddin Basha", "Asst. Prof.", "CSE", "M.Tech.", "Computer Networks and Network Administration."],
  [175, "K. Rambabu", "Asst. Prof.", "CSE", "M.Tech", "Java Programming and Spring Boot."],
  [176, "Sk. Rafi", "Asst. Prof.", "CSE", "M.Tech", "Machine Learning for Women Safety and Social Prediction."],
  [177, "M. Satyam Reddy", "Asst. Prof.", "CSE", "M.Tech", "Deep Learning for Emotion Prediction and Speech Processing."],
  [178, "K V.Narasimha Reddy", "Asst. Prof.", "CSE", "M.Tech", "Cloud Infrastructure and DevOps."],
  [179, "Y. Chandana", "Asst. Prof.", "CSE", "M.Tech", "Software Engineering and Agile Methodologies."],
  [180, "D. Venkata Reddy", "Asst. Prof.", "CSE", "M.Tech", "Cyber Security and Ethical Hacking."],
  [181, "R. Sravan Kumar", "Asst. Prof.", "CSE", "M.Tech", "Data Analytics and Visualization."],
  [182, "G. Saranya", "Asst. Prof.", "CSE", "M.Tech", "Artificial Intelligence and Expert Systems."],
  [183, "M. Venkata Rao", "Asst. Prof.", "CSE", "MCA., M.Tech.", "Object Oriented Programming and C++."],
  [184, "M. Suneetha", "Asst. Prof.", "CSE", "M,Tech", "Web Services and Microservices."],
  [185, "T. G. Ramnadh Babu", "Asst. Prof.", "CSE", "M.Tech", "Mobile Application Development (Flutter/Android)."],
  [186, "S. Venkateswara Rao", "Asst. Prof.", "CSE", "M.Tech", "Computer Graphics and Multimedia."],
  [187, "Ch. Rajani", "Asst. Prof.", "CSE", "MCA., M.Tech", "Data Mining and Business Intelligence."],
  [188, "M. Suresh", "Asst. Prof.", "CSE", "MCA., M.Tech", "Internet and Web Programming."],
  [189, "Abburi Ramesh", "Asst. Prof.", "CSE", "M.Tech", "Algorithms Design and Analysis."],
  [190, "P. Solman", "Asst. Prof.", "CSE", "M.Tech", "Formal Languages and Automata Theory."],
  [191, "M. Koteswara Rao", "Asst. Prof.", "CSE", "M.Tech", "Computer Organization and Architecture."],
  [192, "B. Dileep Kumar", "Asst. Prof.", "CSE", "M.Tech", "Distributed Computing."],
  [193, "Pudota.Sireesha", "Asst. Prof.", "CSE", "M.Tech", "Software Project Management."],
  [194, "D.V. Padmavathi", "Asst. Prof.", "CSE", "M.Tech", "Data Structures using C."],
  [195, "S. Deva Raju", "Asst. Prof.", "CSE", "M.Tech", "Compiler Design and Parsing."],
  [196, "B. Sathish Kumar", "Asst. Prof.", "CSE", "M.Tech", "Artificial Intelligence."],
  [197, "A. Thanuja", "Asst. Prof.", "CSE", "M.Tech", "Big Data Tools (Hadoop/Spark)."],
  [198, "P. Ramadevi", "Asst. Prof.", "CSE", "M.Tech", "Machine Learning Techniques."],
  [199, "R. Sowjanya", "Asst. Prof.", "CSE", "M.Tech", "Deep Learning Applications."],
  [200, "K. V. Pavan Kumar", "Asst. Prof.", "CSE", "M.Tech", "Natural Language Processing."],
  [201, "Kakkera.Prasanthi", "Asst. Prof.", "CSE", "M.Tech", "Cloud Security."],
  [202, "B. Yesaiah", "Asst. Prof.", "CSE", "M.Tech", "Information Retrieval Systems."],
  [203, "Sk. Reshma", "Asst. Prof.", "CSE", "M.Tech", "Software Testing."],
  [204, "D.Malleswari", "Asst. Prof.", "CSE", "M.Tech", "Database Security."],
  [205, "D. Thabitha", "Asst. Prof.", "CSE", "M.Tech", "Web Application Security."],
  [206, "M. Sai Yaswanth", "Asst. Prof.", "CSE", "M.Tech", "Full Stack Development."],
  [207, "N.Laskshmi Gayatri", "Asst. Prof.", "CSE", "M.Tech", "Python for Machine Learning."],
  [208, "Ch.Chandra Sekhar", "Asst. Prof.", "CSE", "M.Tech", "Computer Networks."],
  [209, "P.Pranavi", "Asst. Prof.", "CSE", "M.Tech", "Cloud Platforms (AWS/Azure)."],
  [210, "S.Sai Charan Reddy", "Asst. Prof.", "CSE", "M.Tech", "Operating Systems Internals."],
  [211, "S.Akhilesh", "Asst. Prof.", "CSE", "M.Tech", "Computer Vision."],
  [212, "M.Ganesh", "Asst. Prof.", "CSE", "M.Tech", "Data Science with R."],
  [213, "Ch.Vinay Santhosh", "Asst. Prof.", "CSE", "M.Tech", "DevOps and CI/CD."],
  [214, "B.Venkaiah Chowdary", "Asst. Prof.", "CSE", "M.Tech", "Embedded Systems Programming."],
  [215, "M.Sanjeev kumar", "Asst. Prof.", "CSE", "M.Tech", "Database Optimization."],
  [216, "M.Narasimha Rao", "Asst. Prof.", "CSE", "M.E", "Design Patterns and Architecture."],
  [217, "B.V.V.H.Chandra Sekhar", "Asst. Prof.", "CSE", "M.Tech", "Agile Software Engineering."],
  [218, "N.Jaya chandra", "Asst. Prof.", "CSE", "M.E", "Network Routing Protocols."],
  [219, "Ch.V.Satyannarayana", "Asst. Prof.", "CSE", "M.Tech", "Parallel Processing."],
  [220, "S.Govinda Rajan", "Asst. Prof.", "CSE", "M.Tech", "Information Systems."],
  [221, "A.Vamsi", "Asst. Prof.", "CSE", "M.Tech", "Software Quality Metrics."],
  [222, "N.Naresh", "Asst. Prof.", "CSE", "M.Tech", "Cyber Defense Strategies."],
  [223, "G.V.Neelimadhavi", "Asst. Prof.", "CSE", "M.Tech", "Human Computer Interaction."],
  [224, "T.Saranya", "Asst. Prof.", "CSE", "M.Tech", "Semantic Web Technologies."],
  [225, "V.Swamulu", "Asst. Prof.", "CSE", "M.Tech", "Deep Neural Networks."],
  [226, "A.Ankarao", "Asst. Prof.", "CSE", "M.Tech", "Data Mining."],
  [227, "M.Mounika naga Bhavani", "Asst. Prof.", "CSE", "M.Tech", "Computer Architecture."],
  [228, "V.Karuna Kumar", "Asst. Prof.", "CSE", "M.Tech", "Distributed Ledger Technologies."],
  [229, "Y.Neelima", "Asst. Prof.", "CSE", "M.Tech", "Algorithm Engineering."],
  [230, "B.N.V.Udaya Lakshmi", "Asst. Prof.", "CSE", "M.Tech", "Cloud Storage Systems."],
  [231, "P.Gayatri", "Asst. Prof.", "CSE", "M.Tech", "Artificial Intelligence."],
  [232, "G.Kaoshik", "Asst. Prof.", "CSE", "M.Tech", "Web Development."],
  [233, "GVVSS.Vijayasaradhi", "Asst. Prof.", "CSE", "M.Tech", "Operating Systems."],
  [234, "G.Karthik", "Asst. Prof.", "CSE", "M.Tech", "Mobile Computing."],
  [235, "Dr. R. Yogesh Rajkumar", "Professor", "CS,DS,AIML", "M.Tech, Ph.D", "Machine Learning, Deep Neural Networks, and Predictive Analytics across emerging domains."],
  [236, "Dr. B. Naveen Kumar", "Assoc. Professor", "CS,DS,AIML", "M.Tech, Ph.D", "Cyber Threat Intelligence, Data Mining, and Applied Artificial Intelligence."],
  [237, "P. Srinivasa Rao", "Asst. Prof.", "CS,DS,AIML", "MCA., M.Tech", "Data Structures, Database Systems, and Cloud Integration."],
  [238, "N. Siva Ramakrishna", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Big Data Analytics, Hadoop Ecosystem, and Apache Spark."],
  [239, "D. Sreekanth", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Machine Learning Algorithms, Supervised Learning, and Statistical Modeling."],
  [240, "G. Nageswara Rao", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Cyber Security Fundamentals, Vulnerability Assessment, and Penetration Testing."],
  [241, "G. Mahesh Babu", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Deep Learning Architectures, Computer Vision, and Image Classification."],
  [242, "P. Yedukondalu", "Asst. Prof.", "CS,DS,AIML", "M,Tech", "Natural Language Processing, Text Mining, and Sentiment Analysis."],
  [243, "J. Syam Babu", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Data Visualization, Business Intelligence, and Tableau/PowerBI."],
  [244, "M. Revathi", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Reinforcement Learning and Intelligent Autonomous Systems."],
  [245, "A. Veema Rao", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Information Security, Network Defense, and Firewall Management."],
  [246, "Ch. Sita Maalakshmi", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Feature Engineering, Predictive Modeling, and Python for Data Science."],
  [247, "P. Naga Lakshmi", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Blockchain Development, Smart Contracts, and Cryptography."],
  [248, "B. Sireesha", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Cloud Security Protocols and Distributed Computing."],
  [249, "G. Sindhura Silpa", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Ethical Hacking, Malware Analysis, and Incident Response."],
  [250, "V. Sobha Rani", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Data Wrangling, ETL Pipelines, and Data Warehousing."],
  [251, "G. V. Anjaneyulu", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Time Series Forecasting and Econometric Modeling."],
  [252, "E. Rukmini Devi", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "IoT Security, Sensor Networks, and Edge Computing Defense."],
  [253, "B. Narender Reddy", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Generative AI, Large Language Models, and Prompt Engineering."],
  [254, "G. Sai Sindhura", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Big Data Governance, Data Privacy, and Compliance Frameworks."],
  [255, "K. Ayyappa Kumar", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Cyber Forensics and Cyber Crime Investigation."],
  [256, "Sk. Nagoor Babu", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Deep Neural Networks for Healthcare Diagnostics."],
  [257, "R. Rambabu", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Web Mining and Recommender Systems."],
  [258, "Sk. Nusrath Parveen", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Network Intrusion Detection Systems using ML."],
  [259, "M. Sampath Kumar", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "High Performance Computing for Deep Learning."],
  [260, "V. V. Abhilasha", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Autonomous Agents and Robotics Control."],
  [261, "Ch. Padma", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Data Ethics, Fair AI, and Model Interpretability."],
  [262, "T. Rajani", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Cloud Data Lakes and Distributed File Systems."],
  [263, "M. Jhansi Lakshmi", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Cyber Risk Assessment and Threat Hunting."],
  [264, "U. Nirmala", "Asst. Prof.", "CS,DS,AIML", "M,Tech", "Neural Machine Translation and Speech Recognition."],
  [265, "G. Jeevana Manikanta", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Social Network Analysis and Graph Neural Networks."],
  [266, "A.Sridhar", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Applied Statistics and Hypothesis Testing in AI."],
  [267, "M.Narendra Bhupati", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Zero Trust Architecture and Endpoint Security."],
  [268, "G.Shankar", "Asst. Prof.", "CS,DS,AIML", "M.E", "Computer Vision in Industrial Automation."],
  [269, "L.Keerthi teja", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Data Analytics for Smart Cities."],
  [270, "K.Pavana", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Cyber Physical Systems Security."],
  [271, "V.Srinivasarao", "Asst. Prof.", "CS,DS,AIML", "M.Tech", "Big Data Pipeline Architectures."],
  [272, "P. Mallika", "Asst. Prof.", "CSE (AI)", "M.Tech", "AI Foundations, Knowledge Engineering, and Semantic Reasoning."],
  [273, "T. Anil Kumar", "Asst. Prof.", "CSE (AI)", "M.Tech", "Heuristic Search, Game Theory, and Evolutionary Computation."],
  [274, "M. Praveen", "Asst. Prof.", "CSE (AI)", "M.Tech", "Deep Learning Frameworks (TensorFlow/PyTorch)."],
  [275, "M. Harika", "Asst. Prof.", "CSE (AI)", "M.Tech", "Cognitive Computing and Intelligent Virtual Assistants."],
  [276, "Sk. Shameem Ahammad", "Asst. Prof.", "CSE (AI)", "M.Tech", "AI in Healthcare and Medical Imaging Diagnostics."],
  [277, "L. Sai", "Asst. Prof.", "CSE (AI)", "M.Tech", "Bio-inspired Computing and Swarm Intelligence."],
  [278, "V.Kishore babu", "Asst. Prof.", "CSE (AI)", "M.Tech", "Robotic Process Automation and AI Bots."],
  [279, "V.Suneel Babu", "Asst. Prof.", "CSE (AI)", "M.Tech", "Pattern Recognition and Feature Extraction."],
  [280, "T.Rajesh", "Asst. Prof.", "CSE (AI)", "M.Tech", "Automated Planning and Decision Support Systems."],
  [281, "P.Bala Sampathgoud", "Asst. Prof.", "CSE (AI)", "M.Tech", "Edge AI and Micro-controllers."],
  [282, "N.Bakthavachulu", "Asst. Prof.", "CSE (AI)", "M.Tech", "Explainable AI and Model Verification."],
  [283, "J.Sunil Kumar", "Asst. Prof.", "CSE (AI)", "M.Tech", "Natural Language Understanding and Conversational AI."],
  [284, "Dr. B. Jhansi Vazram", "Professor & HOD", "IT", "M.Tech., Ph.D.", "HOD of Information Technology & CSE (AI); ORCID: 0000-0002-5550-9651; Scopus: 26326882700; Scholar: DGdDxHEAAAAJ; Vidwan: 319695; WoS: HJZ-2915-2023; 30+ publications, 3 books, BoS Chairman R16/R19/R20/R23."],
  [285, "Dr. R. Satees Kumar", "Professor", "IT", "M.Tech., Ph.D.", "Cloud Computing, Distributed Virtualization, and Service Oriented Architecture."],
  [286, "Dr. Motrurai. Sireesha", "Assoc. Professor", "IT", "M.Tech., Ph.D.", "Web Technologies, Mobile Application Platforms, and Software Engineering."],
  [287, "Dr. V. Surya Narayana", "Assoc. Professor", "IT", "M.Tech., Ph.D.", "Data Mining, Information Security, and Cryptography."],
  [288, "Dr. K. Suresh Babu", "Assoc. Professor", "IT", "M.Tech., Ph.D.", "Internet of Things, Embedded Controllers, and Wireless Networking."],
  [289, "Dr. K. Soma Sekhar", "Assoc. Professor", "IT", "M.Tech., Ph.D.", "Database Performance Tuning and Big Data Query Engines."],
  [290, "Dr. Sk. Mohammed Jany", "Assoc. Professor", "IT", "M.Tech., Ph.D.", "Computer Networks, Cyber Security, and Software Defined Networks."],
  [291, "U. Vijay Kumar", "Asst. Prof.", "IT", "M.Tech", "Object Oriented Programming and Full Stack Engineering."],
  [292, "T. Venkata Manohar", "Asst. Prof.", "IT", "M.Tech", "Software Quality Metrics and Agile Project Management."],
  [293, "Kambhampati.Sriseeha", "Asst. Prof.", "IT", "M.Tech", "Web Mining and Information Retrieval."],
  [294, "P. Neelima", "Asst. Prof.", "IT", "M.Tech", "Python Programming and Data Analytics."],
  [295, "P. Vijaya Lakshmi", "Asst. Prof.", "IT", "MCA., M.Tech", "Database Management Systems and Web Applications."],
  [296, "M. Raveendra Babu", "Asst. Prof.", "IT", "M.Tech", "Network Security Protocols and Firewall Administration."],
  [297, "B. Veera Brahmam", "Asst. Prof.", "IT", "M.Tech", "Cloud Native Services and Microservices."],
  [298, "G. Nagendram", "Asst. Prof.", "IT", "M.Tech", "Mobile Computing and Android App Architecture."],
  [299, "N B S Vijay Kumar", "Asst. Prof.", "IT", "M.Tech", "Operating Systems and System Programming."],
  [300, "P. Santhi", "Asst. Prof.", "IT", "M.Tech", "Data Structures and Algorithm Design."],
  [301, "Noorbasha Moulali", "Asst. Prof.", "IT", "M.Tech", "Computer Organization and Architecture."],
  [302, "Y. Suhasini", "Professor", "MCA", "M.C.A", "Object Oriented Software Development, Database Management, and Enterprise Applications."],
  [303, "P. Revathi", "Asst. Prof.", "MCA", "M.C.A", "Web Technologies, Java Programming, and Frontend Frameworks."],
  [304, "R. Bhima Naik", "Asst. Prof.", "MCA", "M.C.A", "Cloud Application Development and System Analysis."],
  [305, "A. Papa Rao", "Asst. Prof.", "MCA", "M.C.A", "Data Structures, Algorithms, and Software Engineering."],
  [306, "D. Lakshmi Dheeraja", "Asst. Prof.", "MCA", "M.C.A", "Python Programming and Database Administration."],
  [307, "G. Sai Krishna", "Asst. Prof.", "MCA", "M.C.A", "Operating Systems and Shell Scripting."],
  [308, "N. Chandra Sekhara Cahri", "Asst. Prof.", "MCA", "M.C.A", "Web Application Development and PHP/MySQL."],
  [309, "B. Jyothi", "Asst. Prof.", "MCA", "M.C.A", "E-Commerce Technologies and Information Systems."],
  [310, "A. Aruna Kumari", "Asst. Prof.", "MCA", "M.C.A", "Software Testing Methodologies and Quality Assurance."],
  [311, "G. Ravi Purnachandra Rao", "Asst. Prof.", "MCA", "M.C.A", "Network Administration and IT Infrastructure."],
  [312, "Sk. Nayab Rasool", "Asst. Prof.", "MCA", "M.C.A", "Data Analytics and Reporting Tools."],
  [313, "B. Prasanthi", "Asst. Prof.", "MCA", "M.C.A", "Object Oriented Analysis and Java Technologies."],
  [314, "Dr. M. Aravind", "Professor", "MBA", "M.B.A., Ph.D", "Financial Management, Investment Analysis, and Corporate Finance."],
  [315, "Dr. P. Pattabhiram", "Professor", "MBA", "M.B.A., Ph.D", "Marketing Management, Consumer Behavior, and Brand Strategy."],
  [316, "Dr. K. Anil Kumar", "Assoc. Professor", "MBA", "MBA, M.Phil., Ph.D", "Human Resource Management, Organizational Behavior, and Leadership."],
  [317, "T. Mallikarjuna Rao", "Assoc. Professor", "MBA", "M.B.A", "Operations Management, Logistics, and Supply Chain Management."],
  [318, "I. Sridhar", "Assoc. Professor", "MBA", "M.B.A.", "Strategic Management, International Business, and Entrepreneurship."],
  [319, "Dr. Y. Anki Reddy", "Asst. Prof. & HOD", "MBA", "MBA., Ph.D", "HOD of Management Studies; Academic Council Member; Financial Analytics and Banking Systems."],
  [320, "Dr. G. Anil Kumar", "Asst. Prof.", "MBA", "MBA., Ph.D", "Business Research Methods, Quantitative Techniques, and Data Analytics."],
  [321, "D. Lakshmi Sowjanya", "Asst. Prof.", "MBA", "M.B.A.", "Managerial Economics and Financial Accounting."],
  [322, "Sd. Salma", "Asst. Prof.", "MBA", "M.B.A.", "Digital Marketing, Social Media Analytics, and Advertising."],
  [323, "V. Hima Bindu", "Asst. Prof.", "MBA", "M.B.A.", "Talent Management and Employee Relations."],
  [324, "D. Satish Babu", "Asst. Prof.", "MBA", "M.B.A.", "Retail Management and Customer Relationship Management."],
  [325, "N. Usha Deepa Sundari", "Asst. Prof.", "MBA", "M.B.A.", "Business Ethics and Corporate Governance."],
  [326, "P. Krishna Sunil", "Asst. Prof.", "MBA", "M.B.A.", "Services Marketing and Product Management."],
  [327, "G. Naga Raju", "Asst. Prof.", "MBA", "M.B.A.", "Total Quality Management and Lean Operations."],
  [328, "M. Rajesh Babu", "Asst. Prof.", "MBA", "M.B.A.", "Portfolio Management and Security Analysis."],
  [329, "R. Ravi Kanth", "Asst. Prof.", "MBA", "M.B.A.", "Business Communication and Soft Skills Training."],
  [330, "V. Hanimi Reddy", "Asst. Prof.", "MBA", "M.B.A.", "Rural Marketing and Agri-business Management."],
  [331, "J. Rajesh", "Asst. Prof.", "MBA", "M.B.A.", "Project Management and Feasibility Studies."],
  [332, "S. Yohanu", "Asst. Prof.", "MBA", "M.B.A.", "Industrial Relations and Labour Laws."],
  [333, "T. Swathi", "Asst. Prof.", "MBA", "M.B.A.", "Enterprise Resource Planning and Business Systems."],
  [334, "D. Nageswara Rao", "Asst. Prof.", "MBA", "M.B.A.", "Financial Derivatives and Risk Management."],
  [335, "A. Naga Raju", "Asst. Prof.", "MBA", "M.B.A.", "International Trade and Export Management."],
  [336, "Sk. Nagura", "Asst. Prof.", "MBA", "M.B.A.", "Microfinance and Rural Banking."],
  [337, "Md. Atheek", "Asst. Prof.", "MBA", "M.B.A.", "Business Analytics and Decision Science."],
  [338, "Dr. K. P. Lakshmi", "Professor & HOD (BS&H)", "ENG", "M.A., M.Phil., Ph.D.", "Dean Student Affairs & HOD of Basic Sciences & Humanities; Academic Council member; English Language Teaching and Indian Writing in English."],
  [339, "Dr. V. Aruna", "Assoc. Professor", "ENG", "M.A., Ph.D.", "Communicative English, Phonetics, and Soft Skills."],
  [340, "Dr. G. Radha Krishna Murthy", "Assoc. Professor", "ENG", "M.A., M.Phil, Ph.D", "Linguistics, Modern English Literature, and Grammar."],
  [341, "Z. Mohana Rao", "Assoc. Professor", "ENG", "M.A.", "Professional Communication and Technical Writing."],
  [342, "Dr. K. Mugeshpillai", "Assoc. Professor", "ENG", "M.A., M.Phil, Ph.D", "Comparative Literature and Literary Criticism."],
  [343, "Dr. J. Rama Krishnan", "Assoc. Professor", "ENG", "M.A., M.Phil, Ph.D", "English for Specific Purposes and Language Testing."],
  [344, "Dr. Sk. Rafi", "Asst. Prof.", "ENG", "M.A., M.Phil., Ph.D.", "English Literature and Interactive Teaching Methodologies."],
  [345, "M. Purna Chandra Rao", "Asst. Prof.", "ENG", "M.A", "Communication Skills and Personality Development."],
  [346, "Ch. Krishna", "Asst. Prof.", "ENG", "M A., MBA", "Business English and Corporate Communication."],
  [347, "P. Prabhu Preethi", "Asst. Prof.", "ENG", "M.A.", "Language Lab Instruction and Accent Neutralization."],
  [348, "SK. A. Riyaz Basha", "Asst. Prof.", "ENG", "M.A.", "Functional English and Vocabulary Enrichment."],
  [349, "R. Chandra Mouli", "Asst. Prof.", "ENG", "M.A.", "English Grammar and Composition."],
  [350, "M. Indhira", "Asst. Prof.", "ENG", "M.A.", "Reading and Listening Comprehension Strategies."],
  [351, "P. V. Aditya", "Asst. Prof.", "ENG", "M.A.", "Creative Writing and Public Speaking."],
  [352, "V. Pavitra", "Asst. Prof.", "ENG", "M.A.", "English for Competitive Examinations."],
  [353, "Dr. Sk. Mohiddin Shaw", "Professor", "Maths", "M.Sc., M.Phil., Ph.D.", "Differential Equations, Numerical Analysis, and Boundary Value Problems."],
  [354, "Dr. N. C. H. Ramgopal", "Professor", "Maths", "M.Sc,, Ph.D", "Fluid Dynamics, Mathematical Modelling, and Heat Transfer."],
  [355, "Dr. J. Venkatesan", "Professor", "Maths", "M.Sc,, Ph.D", "Operations Research, Linear Programming, and Queuing Theory."],
  [356, "Dr. P. Palani", "Professor", "Maths", "M.Sc,, Ph.D", "Applied Mathematics and Cryptographic Algorithms."],
  [357, "Dr. R. Mohana Ramana", "Assoc. Professor", "Maths", "M.Sc., Ph.D.", "Graph Theory and Discrete Mathematical Structures."],
  [358, "Dr. Ch. Maheswari", "Assoc. Professor", "Maths", "M.Sc., M.Phil., Ph.D.", "Algebra and Fuzzy Mathematical Models."],
  [359, "D. Umasankar", "Assoc. Professor", "Maths", "M.Sc., M.Phil.", "Engineering Mathematics and Complex Analysis."],
  [360, "M. Prasad", "Assoc. Professor", "Maths", "M.Sc", "Probability, Statistics, and Stochastic Processes."],
  [361, "A. Aparna", "Assoc. Professor", "Maths", "M.Sc.", "Vector Calculus and Integral Transforms."],
  [362, "Dr. N. Ravi Babu", "Asst. Prof.", "Maths", "M.Sc., M.Phil., Ph.D", "Numerical Optimization and Scientific Computing."],
  [363, "Dr. M. Ankarao", "Asst. Prof.", "Maths", "M.Sc., Ph.D", "Applied Differential Geometry and Wavelets."],
  [364, "Jakka Radhika", "Asst. Prof.", "Maths", "M.Sc", "Linear Algebra and Matrix Theory."],
  [365, "Sd. Roshini Banu", "Asst. Prof.", "Maths", "M.Sc", "Calculus and Analytical Geometry."],
  [366, "V. Radha", "Asst. Prof.", "Maths", "M.Sc", "Statistical Quality Control and Biostatistics."],
  [367, "Y. C. V. Saida Rao", "Asst. Prof.", "Maths", "M.Sc", "Discrete Mathematics and Graph Algorithms."],
  [368, "K. Harischandra Prasad", "Asst. Prof.", "Maths", "M.Sc., M.Phil.", "Numerical Methods and MATLAB Applications."],
  [369, "Sk. Shareef", "Asst. Prof.", "Maths", "M.Sc", "Partial Differential Equations."],
  [370, "V. Siva Rama Prasad", "Asst. Prof.", "Maths", "MSC", "Engineering Mathematics I & II."],
  [371, "U. Sai Kumar", "Asst. Prof.", "Maths", "M.Sc", "Transforms and Vector Analysis."],
  [372, "Ch. Revathi", "Asst. Prof.", "Maths", "M.Sc", "Applied Probability and Random Processes."],
  [373, "K. Uma Rani", "Asst. Prof.", "Maths", "M.Sc", "Fourier Series and Boundary Value Analysis."],
  [374, "S. Lakhmi Bhavani", "Asst. Prof.", "Maths", "M.Sc", "Discrete Structures and Boolean Algebra."],
  [375, "E. Naga Devi", "Asst. Prof.", "Maths", "M.Sc", "Multivariable Calculus and Optimization."],
  [376, "Dr. T. Anjaneyulu", "Professor", "PHY", "M.Sc., M.Phil., Ph.D.", "Condensed Matter Physics, Semiconductor Physics, and Thin Films."],
  [377, "Dr. K. Neeraja", "Professor", "PHY", "M.Sc., M.Phil., Ph.D.", "Materials Science, Dielectric Materials, and Ceramics."],
  [378, "Dr. N. Giridhar Babu", "Professor", "PHY", "M.Sc., Ph.D.", "Solid State Physics, Solar Energy Materials, and Superconductivity."],
  [379, "Dr. V. Poli Reddy", "Professor", "PHY", "M.Sc., M.Phil., Ph.D", "Nanomaterials, Carbon Nanotubes, and Photovoltaics."],
  [380, "Dr. Anandhan Kaliyan", "Professor", "PHY", "M.Sc., Ph.D.", "Quantum Mechanics and Laser Physics."],
  [381, "Dr. Chandra Mohan Jaa", "Assoc. Professor", "PHY", "M.Sc., M.Phil., Ph.D", "Optics, Fiber Optics, and Holography."],
  [382, "Dr. M. Prakasam", "Assoc. Professor", "PHY", "M.Sc., M.Phil., Ph.D", "Spectroscopy and Crystal Growth."],
  [383, "Dr. A. Arunachelam", "Assoc. Professor", "PHY", "M.Sc., Ph.D.", "Ultrasonics, Non-Destructive Testing, and Acoustics."],
  [384, "Dr. Elumalai", "Assoc. Professor", "PHY", "M.Sc., Ph.D.", "Electromagnetic Theory and Plasma Physics."],
  [385, "G.S. John", "Asst. Prof.", "PHY", "M.Sc", "Engineering Physics Lab and Solid State Devices."],
  [386, "A. Anjaneyulu", "Asst. Prof.", "PHY", "M.Sc", "Optoelectronic Devices and Sensors."],
  [387, "A. Raju", "Asst. Prof.", "PHY", "M.Sc", "Thermodynamics and Statistical Mechanics."],
  [388, "M. Naga Sireesha", "Asst. Prof.", "PHY", "M.Sc", "Modern Physics and Nuclear Energy."],
  [389, "J. Parimala", "Asst. Prof.", "PHY", "M.Sc", "Physics of Semiconductor Devices."],
  [390, "S. Srinivasarao", "Asst. Prof.", "PHY", "M.Sc", "Applied Optics and Laser Applications."],
  [391, "N. Sujala", "Asst. Prof.", "PHY", "M.Sc", "Electromagnetic Fields and Waves."],
  [392, "M. Bala Chandrika", "Asst. Prof.", "PHY", "M.Sc,, M.Phil", "Materials Characterization Techniques."],
  [393, "Dr. K. Anji Reddy", "Professor", "CHE", "M.Sc., Ph.D.", "Organic Synthesis, Medicinal Chemistry, and Drug Design."],
  [394, "Dr. G. Somaiah", "Professor", "CHE", "M.Sc,, Ph.d", "Environmental Chemistry, Water Treatment, and Pollution Abatement."],
  [395, "Dr. Manimaran", "Professor", "CHE", "M.Sc,, Ph.D", "Inorganic Chemistry, Coordination Compounds, and Catalysis."],
  [396, "Dr. A. Mohamed Ibraheem", "Professor", "CHE", "M.Sc,, Ph.D", "Polymer Chemistry, Biomaterials, and Corrosion Inhibitors."],
  [397, "Dr. Devarapaga Madhu", "Professor", "CHE", "M.Sc,, Ph.D", "Physical Chemistry, Chemical Kinetics, and Electrochemistry."],
  [398, "Dr. M. Sathiya Seelan", "Professor", "CHE", "M.Sc,, Ph.D", "Analytical Chemistry, Chromatography, and Spectroscopic Analysis."],
  [399, "Dr. A. V. L. N. H. Hariharan", "Professor", "CHE", "M.Sc,, Ph.D", "Industrial Chemistry and Chemical Process Safety."],
  [400, "Dr. P. N. V. V. L. Pramila Rani", "Asst. Prof.", "CHE", "M.Sc., M.Phil., Ph.D", "Nanochemistry and Green Synthesis of Nanoparticles."],
  [401, "Dr. Y. Lakshman Kumar", "Asst. Prof.", "CHE", "M.Sc., Ph.D.", "Bio-inorganic Chemistry and Molecular Modeling."],
  [402, "Dr. K. Santha Kumari", "Asst. Prof.", "CHE", "M.Sc., M.Phil., Ph.D", "Water Quality Analysis and Waste Water Treatment."],
  [403, "G. Nagaraju", "Asst. Prof.", "CHE", "M.Sc", "Advanced Energy Materials & Battery Chemistry; EEE Patent Co-inventor."],
  [404, "G. Sagar Kumar", "Asst. Prof.", "PHY", "M.Sc", "Engineering Physics Laboratory Techniques."],
  [405, "B. Santhi", "Asst. Prof.", "CHE", "M.Sc.", "Chemical Thermodynamics and Phase Equilibria."],
  [406, "B. Srinu", "Asst. Prof.", "CHE", "M.Sc", "Corrosion Science and Engineering Materials."],
  [407, "N. Naga Sindhuja", "Asst. Prof.", "CHE", "M.Sc", "Spectrophotometric Analysis of Trace Metals."],
  [408, "K. Sagar Babu", "Asst. Prof.", "CHE", "M.Sc", "Organic Reaction Mechanisms and Stereochemistry."],
  [409, "B. Anil Sai Kumar", "Asst. Prof.", "CHE", "M.Sc", "Fuel Chemistry and Lubricant Technology."],
  [410, "K. Naga Raju", "Asst. Prof.", "CHE", "M.Sc", "Environmental Impact Assessment and Solid Waste Management."],
  [411, "J. Lakshmi", "Asst. Prof.", "CHE", "M.Sc", "Inorganic Reaction Dynamics."],
  [412, "Sk. Alla Nazeer", "Asst. Prof.", "CHE", "M.Sc", "General and Applied Engineering Chemistry."],
  [413, "K. Rajini", "Asst. Prof.", "CHE", "M.Sc", "Polymer Composites and Industrial Coatings."],
  [414, "Dr. K. Sreenivasulu", "Assoc. Professor", "E.S.", "M.Sc., Ph.D", "Environmental Science, Ecology, and Sustainable Energy Management."],
  [415, "Dr. O. Ananda", "Asst. Prof.", "TPC", "M.B.A., Ph.D.", "Training & Placement Cell Coordinator; Corporate Relations and Soft Skills Training."],
  [416, "L. Krishna Reddy", "Physical Director", "P.D.", "M.P.Ed.", "Physical Education Director; Inter-collegiate Athletics and Sports Training."],
  [417, "N. Anjaneyulu", "Physical Director", "P.D.", "M.P.Ed.", "Physical Education Director; Basketball, Cricket and Intramural Tournaments."],
  [418, "P. Vijaya Kumar", "Physical Director", "P.D.", "M.P.Ed.", "Physical Education Director; Volleyball, Indoor Games, and Fitness Development."]
];

console.log('Total faculty processed:', facultyCSVLines.length);
